# General Parameters
BATCH_SIZE: 64
BATCH_SIZE_PEPTIDES: 4096
NUMBER_OF_THREADS: 64
USE_STREAM: FALSE

# Preprocessing Parameters
MAX_N_PEAKS: 100

# Search Parameters
PEPTIDE_MINIMUM_LENGTH: 7
PEPTIDE_MAXIMUM_LENGTH: 42
MAX_MISSED_CLEAVAGES: 1
SEMI_SPECIFIC_CLEAVAGE: False
K: 50
MIN_PEPTIDE_MASS: 500.
MAX_PEPTIDE_MASS: 5000.
N_BUCKETS_NARROW: 2250
N_BUCKETS_OPEN: 12

# Scoring Parameters
FDR: 0.01
MAX_N_FRAGMENTS: 200
TOLERANCE_DALTON: 0.01
MIN_MATCHING_PEAKS : 4
MIN_DELTA_MASS: -150.
MAX_DELTA_MASS: 500.